# conf/config.yaml

defaults:
  - override /training: default

# Global config
server:
  server_address: "0.0.0.0:8080"
  rounds: 3  # Number of FL rounds

client:
  fraction_fit: 0.5
  fraction_eval: 0.5
  min_fit_clients: 2
  min_eval_clients: 2
  min_available_clients: 2

training:
  # For local training on client side
  batch_size: 32
  epochs: 5
  validation_split: 0.2

dataset:
  path: "data/Beijing.csv"
  # If your dataset has different columns or file path, adjust here.
